### ISSUE TITLE
CSS - Ainda não está com o CSS final como desenhado.

### ISSUE THREAD

**Issue by nuno3cmonteiro** [prika/UAE-Future#12]

**Comment by prika** [comment]
Indicações mais especificas por favor

**Comment by nuno3cmonteiro** [comment]
Basicamente são as esquinas (triangulos) e se possível as previews do video ocuparem todo o espaço sem aparecer as barras pretas horizontais.

**Comment by prika** [comment]
Os videos ocuparem todo o espaço é causado pelo youtube, se meterem lá as imagens pelo cms ficam assim.
As esquinas dos triângulos preciso que actualizem a imagem "/sysimages/cornerTopPopup.png"

**Comment by sabbath83** [comment]
Actualizado

**Comment by prika** [comment]
Acho que ainda não está a [imagem certa](https://github.com/prika/UAE-Future/blob/master/sysimages/cornerTopPopup.png)

Repara que esta é transparente e cinza escuro no canto, a que está lá é branca e cinza transparente.

**Comment by sabbath83** [comment]
Desculpa ainda não tinhamos feito publish. Podes confirmar agora sff?

**Comment by prika** [comment]
Confirmado e ok.
