### ISSUE TITLE
Issues Responsive

### ISSUE THREAD

**Issue by nuno3cmonteiro** [prika/UAE-Future#15]
- [x]  Popups das cards aparecem com scroll horizontal

**Comment by prika** [comment]
Relativamente ao datepicker, preciso que alterem a estrutura para a seguinte:
[Filters-example.txt](https://github.com/prika/UAE-Future/files/416319/Filters-example.txt)

**Comment by prika** [comment]
Ponto 2 será passado para outra issue sobre o mesmo problema. ( #18  )
