### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by brduca** [prika/UAE-Future#21]
Estão faltando dados na fancybox. 
Faltam informações:
- [x] imagem
- [x] localização
- [x] categorias
- [x] tags

O serviço do sitefinity não expõe estes dados.

**Comment by prika** [comment]
Em árabe aparece um `<h2>` que não faço ideia do que seja.
![screen shot 2016-08-23 at 22 58 48](https://cloud.githubusercontent.com/assets/821699/17911411/4c3c170c-6985-11e6-9b2c-fe9fab8c9b71.png)

**Comment by sabbath83** [comment]
Já foi removido.
