### ISSUE TITLE
Pagina News

### ISSUE THREAD

**Issue by sabbath83** [prika/UAE-Future#24]
Cor do Icon do filtro não é igual ao da cor que é usado na card.

**Comment by sabbath83** [comment]
Neste momento actualizamos a cor dos cards para (#8C75EC)

**Comment by prika** [comment]
Por favor, explica-me como está esta situação. O que está feito e o que é preciso?

**Comment by sabbath83** [comment]
Ainda está por resolver. Preciso que actualizes no css a cor do card para (#8C75EC). Porque se fores ao site vais ver que a cor do icon é diferente da cor do texto.

**Comment by prika** [comment]
Estás a falar deste caso? É que aquilo é uma imagem.

![screen shot 2016-08-26 at 00 00 06](https://cloud.githubusercontent.com/assets/821699/17988743/209fde48-6b20-11e6-9a93-ab3cf4ac8d8f.png)

**Comment by sabbath83** [comment]
Pois é exatamente esse caso. A cor tem que ser igual.

**Comment by prika** [comment]
Basta alterar a imagem news.png dentro da pasta checkbox
