### ISSUE TITLE
DateTimePicker Tweaks and others

### ISSUE THREAD

**Issue by ghost** [prika/UAE-Future#25]
- [x] Adicionar a class .form-group aos css (como existe no bootstrap)
  .form-group {
  margin-bottom: 15px;
  }
- [x] Adicionar height: 34px; à classe .input-group .form-control dos ficheiros +00_base.css (existente tambem no boostrap na class .form-control)
- [x] Alterar todos os tipos de letra em Arabe  (ficheiro 001) para AraHamahAlFidaa-Regular
  [AraHamahAlFidaa-Regular.zip](https://github.com/prika/UAE-Future/files/424585/AraHamahAlFidaa-Regular.zip)
  Testei alterar todos os @font-face.src para url("../fonts/AraHamahAlFidaa-Regular.ttf") e funcionou bem.
  Vejam a melhor maneira

**Comment by prika** [comment]
Já adicionei o css pedido e alterei os srcs dos fontface para essa font, não é a melhor forma porque no inspect o nome da font será o mesmo que estava, mas desta forma de quiserem colocar fonts árabes diferentes por exemplo para titulos e outra para corpo de texto é facil de alterar.
