### ISSUE TITLE
Adicionar aos CSS

### ISSUE THREAD

**Issue by sabbath83** [prika/UAE-Future#26]
Adicionar sff:
- 001_guide linha 655 "direction: rtl;"

Adicionar o hover no Change Language:
-Para já adicionei no - 001_guide e no 000_guide linha 1187  #footer a#changeLanguage:hover

---

Alterações ao Botão de Share e favoritos: (como estão não era possivel utilizar) 
- No 000_guide  na linha 775 adicionar "float:right;" e remover na linha 1502 "float:right;" 
- No 001_guide na linha 722 adicionar "float:left;"

**Comment by prika** [comment]
Está adicionado o hover do language.

Qual é o problema dos botões Share e Favoritos? 
Preciso perceber o que é porque eu não tenho acesso a essas linhas 775 nem 722, estou a desenvolver os estilos por sass.

**Comment by sabbath83** [comment]
Só falta adicionar "direction:rtl" para os formulários do contactos e criar utilizador.

Com a ultima alteração dos css  os botões Share e Favoritos ficaram resolvidos em web.

Mas em Mobile os Botões não funcionam.

**Comment by prika** [comment]
O direction já coloquei.

Os botões não funcionam? Como assim?

**Comment by sabbath83** [comment]
Este problema está descrito na issue #30 . Por isso pode ser fechada.
