### ISSUE TITLE
Page Header Content not appear correctly over Mobile

### ISSUE THREAD

**Issue by sabbath83** [prika/UAE-Future#28]
![4-1](https://cloud.githubusercontent.com/assets/15090371/17887039/7555c41c-691c-11e6-82f3-b08596e30c70.jpg)

**Comment by prika** [comment]
O problema é no header ou no texto em baixo?

**Comment by nuno3cmonteiro** [comment]
No texto em baixo que está a desaparecer. O Header está ok.

**Comment by prika** [comment]
Está corrigido. Na próxima actualização de css já fica direitinho.

**Comment by sabbath83** [comment]
Já está actualizado.
