### ISSUE TITLE
Imagem e texto do banner

### ISSUE THREAD

**Issue by ghost** [prika/UAE-Future#4]
É possivel dar um jeito ao banner para quando a imagem não é suficiente grande, esticar o suficiente para não acontecer o mesmo que na imagem a baixo.
Quando o texto é comprido, torna-se impossivel chegar ao botão a baixo "Learn More".

Podem verificar na homepage do endereço http://54.93.89.184/ onde podem ver ambos os problemas

![image](https://cloud.githubusercontent.com/assets/3720827/17556071/f3b0d738-5f09-11e6-86ee-6eb6b47f285c.png)

**Comment by prika** [comment]
@KashmirTheOne 
O problema da imagem foi causado porque tinha aumentado as imagens para não haver falhas à volta quando se faz o parallax com o mouse, penso que ficou corrigido.

Em relação ao texto não era suposto ser um testamento por isso fiz um truncate para que o titulo não passe de 2 linhas e o bloco de texto limitei a 5 linhas.
