### ISSUE TITLE
No dicionário na listagem de palavras...

### ISSUE THREAD

**Issue by tiago-castro** [prika/UAE-Future#7]
[http://54.93.89.184/dictionary](http://54.93.89.184/dictionary)
Colocar um scroll listagem de palavras quando atingir um numero de palavras 10 ou assim...
![capture](https://cloud.githubusercontent.com/assets/20979397/17607318/027161de-601d-11e6-8e1c-9b8efa1eb563.PNG)

**Comment by prika** [comment]
Coloquei scroll para já para desenrascar mas acho que não ficará muito bem.
Preciso que ajudes com umas coisas aí: 
- [x] Retirar o css inline
- [x] Colocar uma `<div class="contentWordsScroll">` dentro do  `.containerWords` a envolver tudo o que está dentro dele;
- [x] No final entre a tal div com a class `.contentWordsScroll` e o fim do  `.containerWords` preciso que coloques 2 elementos:

```
<a href="javascript:void(0)" class="buttonUp"></a>
<a href="javascript:void(0)" class="buttonDown"></a>
```

**Comment by sabbath83** [comment]
já adicionei. Podes confirmar se é isto que era pretendido? Adicionei uns dados para teste que quero apagar :). 
http://54.93.89.184/dictionary

**Comment by prika** [comment]
Coloca mais dados de teste por favor. Não chego a colocar scroll porque tem poucos elementos.

**Comment by prika** [comment]
Acho que podes substituir o `javascript:void(0)` do href pelo `javascript:loadWord('af50...')"`

O elemento `<a>` tem o click no href

**Comment by sabbath83** [comment]
Já adicionei mais dados. E já fiz a alteração que pediste.

**Comment by prika** [comment]
Está ok!
